/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PenjualIndexRouteImport } from './routes/penjual.index'
import { Route as PenjualIdRouteImport } from './routes/penjual.$id'

const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualIndexRoute = PenjualIndexRouteImport.update({
  id: '/penjual/',
  path: '/penjual/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenjualIdRoute = PenjualIdRouteImport.update({
  id: '/penjual/$id',
  path: '/penjual/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verifikasi': typeof VerifikasiRoute
  '/penjual/$id': typeof PenjualIdRoute
  '/penjual/': typeof PenjualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verifikasi': typeof VerifikasiRoute
  '/penjual/$id': typeof PenjualIdRoute
  '/penjual': typeof PenjualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verifikasi': typeof VerifikasiRoute
  '/penjual/$id': typeof PenjualIdRoute
  '/penjual/': typeof PenjualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verifikasi' | '/penjual/$id' | '/penjual/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verifikasi' | '/penjual/$id' | '/penjual'
  id: '__root__' | '/' | '/verifikasi' | '/penjual/$id' | '/penjual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifikasiRoute: typeof VerifikasiRoute
  PenjualIdRoute: typeof PenjualIdRoute
  PenjualIndexRoute: typeof PenjualIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjual/': {
      id: '/penjual/'
      path: '/penjual'
      fullPath: '/penjual/'
      preLoaderRoute: typeof PenjualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penjual/$id': {
      id: '/penjual/$id'
      path: '/penjual/$id'
      fullPath: '/penjual/$id'
      preLoaderRoute: typeof PenjualIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifikasiRoute: VerifikasiRoute,
  PenjualIdRoute: PenjualIdRoute,
  PenjualIndexRoute: PenjualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
